services:
    app:
        container_name: home_sauron_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php-dev.ini
            - ${LOCAL_STORAGE_PATH}:${LOCAL_STORAGE_PATH}
        depends_on:
            - psql
            - redis
            - nginx
        networks:
            - home_sauron-local-network
        ports:
            - "3000:3000"

    psql:
        container_name: home_sauron_psql
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: app
        volumes:
            - home_sauron_local_pgdata:/var/lib/postgresql/data
        ports:
            - "54323:5432"
        networks:
            - home_sauron-local-network

    redis:
        container_name: home_sauron_redis
        image: redis
        command: redis-server --requirepass root --bind 0.0.0.0
        ports:
            - 63790:6379
        networks:
            - home_sauron-local-network

    nginx:
        container_name: home_sauron_nginx
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 8000:80
        networks:
            - home_sauron-local-network

volumes:
    home_sauron_local_pgdata:

networks:
    home_sauron-local-network:
